### PR TITLE
task/update axios

### PR DESCRIPTION
**Pull request by jmetev1**
update axios
# Test Links:
[Landing Page](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/)
[MoreCast 2.0](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/morecast-2)
[Percentile Calculator](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/percentile-calculator)
[MoreCast](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/morecast)
[C-Haines](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/c-haines)
[FireBat](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireBat bookmark](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN,s=9999&f=c7&c=NaN&w=NaN)
[Auto Spatial Advisory (ASA)](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/auto-spatial-advisory)
[HFI Calculator](https://wps-pr-2946.apps.silver.devops.gov.bc.ca/hfi-calculator)

### CODE REVIEW

**Comment by conbrad** [comment]
Some of these compile errors are what I ran into before: https://github.com/bcgov/wps/actions/runs/5292737518/jobs/9579979805?pr=2946#step:4:187

Are you able to reproduce and debug these locally?

**Comment by jmetev1** [comment]
> Some of these compile errors are what I ran into before: https://github.com/bcgov/wps/actions/runs/5292737518/jobs/9579979805?pr=2946#step:4:187
> 
> Are you able to reproduce and debug these locally?

Yes. now I've made it build. But i'm not real happy with it. I took kind of a middle ground between what you were doing before with expecting  error?.response?.data?.detail and this idea: https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript . i spent a few hours trying to add a test for this but gave up.

**Comment by conbrad** [comment]
> > Some of these compile errors are what I ran into before: https://github.com/bcgov/wps/actions/runs/5292737518/jobs/9579979805?pr=2946#step:4:187
> > Are you able to reproduce and debug these locally?
> 
> Yes. now I've made it build. But i'm not real happy with it. I took kind of a middle ground between what you were doing before with expecting error?.response?.data?.detail and this idea: https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript . i spent a few hours trying to add a test for this but gave up.

I like the middle ground you landed on here, the util function is clean. I see you have some tests as well, was there something else specific you wanted to test?

**Comment by conbrad** [comment]
One thing we could also try is the typeguard `isAxiosError` that `axios` ships with: https://dev.to/mdmostafizurrahaman/handle-axios-error-in-typescript-4mf9

**Review by conbrad — APPROVED** [review]

**Review by dgboss — APPROVED** [review]

**Pull request merged**
