### PR TITLE
Updated container diagram

### PR DESCRIPTION
**Pull request by Sybrand**
- Switched to using draw.io (theoretically anyone can now update the diagram using the raw file)
- Updated to show latest changes.

### CODE REVIEW

**Review by conbrad — COMMENTED** [review]
Why not just a link to the draw.io url?

**Comment by Sybrand** [comment]
> Why not just a link to the draw.io url?

1) Not version controlled.
2) On my personal google drive.

**Comment by conbrad** [comment]
> > Why not just a link to the draw.io url?
> 
> 1. Not version controlled.
> 2. On my personal google drive.

Draw.io is version controlled, also you can hook it up to Github repos apparently. I'm just concerned about the maintenance cost of this solution.

**Comment by Sybrand** [comment]
> > > Why not just a link to the draw.io url?
> > 
> > 
> > 
> > 1. Not version controlled.
> > 2. On my personal google drive.
> 
> Draw.io is version controlled, also you can hook it up to Github repos apparently. I'm just concerned about the maintenance cost of this solution.

That's pretty cool. But isn't it giving draw.io write rights to our Github repo? Do you know what the security is around this?
Definitely not paying for a single file - if there's cost involved.

**Review by conbrad — APPROVED** [review]
> That's pretty cool. But isn't it giving draw.io write rights to our Github repo? Do you know what the security is around this?
Definitely not paying for a single file - if there's cost involved.

Looks like they require a wide scope of permissions since Github doesn't make read/write that granular: https://www.reddit.com/r/webdev/comments/iww6y3/why_does_drawio_need_access_to_deploy_keys_access/

**Comment by andrea-williams** [comment]
bottom right corner of diagram - "Legacy Weather Bots" - are we still pulling data from bcfireweatherp1? I thought we'd entirely switched over to WFWX API (but also it feels like I've forgotten everything Morecast related)

**Comment by Sybrand** [comment]
Nope. Still pulling from legacy. It’s a big deal – stuff is going to break again – soon.

From: Andrea Williams ***@***.***>
Reply-To: bcgov/wps ***@***.***>
Date: Tuesday, July 27, 2021 at 9:43 AM
To: bcgov/wps ***@***.***>
Cc: "Strauss, Sybrand IIT:EX" ***@***.***>, Author ***@***.***>
Subject: Re: [bcgov/wps] Updated container diagram (#1168)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


bottom right corner of diagram - "Legacy Weather Bots" - are we still pulling data from bcfireweatherp1? I thought we'd entirely switched over to WFWX API (but also it feels like I've forgotten everything Morecast related)

**Review by andrea-williams — APPROVED** [review]

**Pull request merged**
