### PR TITLE
Create and display missing prediction rows

### PR DESCRIPTION
**Pull request by dgboss**
When data isn't available from the API for a specific date/model/station combination, we need to display a row in the datagrid  with N/A values.
# Test Links:
[Landing Page](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/)
[MoreCast 2.0](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/morecast-2)
[Percentile Calculator](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/percentile-calculator)
[MoreCast](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/morecast)
[C-Haines](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/c-haines)
[FireBat](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireBat bookmark](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN,s=9999&f=c7&c=NaN&w=NaN)
[Auto Spatial Advisory (ASA)](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/auto-spatial-advisory)
[HFI Calculator](https://wps-pr-2682.apps.silver.devops.gov.bc.ca/hfi-calculator)

### CODE REVIEW

**Review by conbrad — APPROVED** [review]
We may want to pull out the `fillInTheBlanks`, and the date interval logic into a isolated functions we can write tests for, but could be done in a follow up PR

**Comment by dgboss** [comment]
> We may want to pull out the `fillInTheBlanks`, and the date interval logic into a isolated functions we can write tests for, but could be done in a follow up PR

Great idea! I will do that first thing tomorrow.

**Comment by conbrad** [comment]
> > We may want to pull out the `fillInTheBlanks`, and the date interval logic into a isolated functions we can write tests for, but could be done in a follow up PR
> 
> Great idea! I will do that first thing tomorrow.

I should clarify unit tests for these functions, I don't think it makes sense to write Cypress e2e tests for anything yet.

**Comment by dgboss** [comment]
> 

Added some tests in https://github.com/bcgov/wps/pull/2682/commits/c192bb13dfe654839d7bcbcaf018cc2c3a57d2ab

**Comment by dgboss** [comment]
> 



> > 
> 
> Added some tests in [c192bb1](https://github.com/bcgov/wps/commit/c192bb13dfe654839d7bcbcaf018cc2c3a57d2ab)

Oops, missed interval logic...coming soon

**Review by andrea-williams — APPROVED** [review]

**Pull request merged**
