### PR TITLE
README badges: issues, license and lifecycle

### LINKED ISSUE #636: Add project lifecycle badge
## No Project Lifecycle Badge found in your readme!
Hello! I scanned your readme and could not find a project lifecycle badge. A project lifecycle badge will provide contributors to your project as well as other stakeholders (platform services, executive) insight into the lifecycle of your repository.
## What is a Project Lifecycle Badge?
It is a simple image that neatly describes your project's stage in its lifecycle. More information can be found in the [project lifecycle badges documentation](https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md).
## What do I need to do?
I suggest you make a PR into your README.md and add a project lifecycle badge near the top where it is easy for your users to pick it up :). Once it is merged feel free to close this issue. I will not open up a new one :)

### PR DESCRIPTION
**Pull request by DerekRoberts**
README badges for issues, license and lifecycle.  Keep whatever helps.  Lifecycle badge resolves #636.

### CODE REVIEW

**Comment by DerekRoberts** [comment]
Are tests failing from forks?  I don't seem to have the rights to create a branch on the source repo.

**Comment by andrea-williams** [comment]
> Are tests failing from forks? I don't seem to have the rights to create a branch on the source repo.

that would appear to be the case, but I don't know for sure. I don't think we've ever had someone make a PR from a fork before.

Do you want me to add you as an approved contributor (or whatever the correct phrasing is) so you can create a branch from our repo? Or I could just copy and paste your change into a branch I create

**Comment by DerekRoberts** [comment]
@andrea-williams Sure!  Whatever is easiest.

**Comment by andrea-williams** [comment]
> @andrea-williams Sure! Whatever is easiest.

Screw it, I'll just make a new branch and copy and paste your changes into it. I'll get an extra 4 LOC attributed to me in Contributions. I'm way behind Sy and Kyubin.

Thanks for your PR (and doing the work for me!) @DerekRoberts !

**Comment by DerekRoberts** [comment]
Replaced by #884

**Pull request closed without merging**
