### PR TITLE
Story/FIREBAT UI improvements/1121

### PR DESCRIPTION
**Pull request by conbrad**
Test: https://wps-pr-1126.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator

- [x] Align prompt icons to right of cell
- [x] Searchable dropdown (risky - lot's of unknowns)
- [x] Dropdown station list consistent with rest of site (name + code combo)
- [x] Click selection of select item should collapse the option list

Empty state and grass cure number input usability improvement added to https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1130

### CODE REVIEW

**Review by tessmgood — APPROVED** [review]
Approved.  1000% better  - searching, selecting, scanning.... sssensational

**Review by Sybrand — APPROVED** [review]
lgtm

**Review by andrea-williams — APPROVED** [review]
I expect @tessmgood might have some thoughts on the X buttons in the dropdowns that don't actually clear the selected item, they just toggle the row's checkbox, but if Tess is happy, I'm happy

**Comment by conbrad** [comment]
> I expect @tessmgood might have some thoughts on the X buttons in the dropdowns that don't actually clear the selected item, they just toggle the row's checkbox, but if Tess is happy, I'm happy

Yep that's one part I neglected to mention in the description -- it's related to the empty state selection stuff I'm working on in https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1130

**Comment by tessmgood** [comment]
> I expect @tessmgood might have some thoughts on the X buttons in the dropdowns that don't actually clear the selected item, they just toggle the row's checkbox, but if Tess is happy, I'm happy

Yes, discussed yesterday. This is glitchy but still a notable improvement. Beyond the 'x' that isn't functioning, if you click in the cell twice (de-selects the text) you can only hit backspace once, after that you can't clear the station. More QA needed. It's still an improvement and I'd love to demo the UI fixes in case it was a detractor for the folks who've seen/tested it.

**Comment by conbrad** [comment]
> > I expect @tessmgood might have some thoughts on the X buttons in the dropdowns that don't actually clear the selected item, they just toggle the row's checkbox, but if Tess is happy, I'm happy
> 
> Yes, discussed yesterday. This is glitchy but still a notable improvement. Beyond the 'x' that isn't functioning, if you click in the cell twice (de-selects the text) you can only hit backspace once, after that you can't clear the station. More QA needed. It's still an improvement and I'd love to demo the UI fixes in case it was a detractor for the folks who've seen/tested it.

@tessmgood feel free to add any other defects to the acceptance criteria in: https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1130

**Pull request merged**
