### PR TITLE
Show/Hide weather models

### PR DESCRIPTION
**Pull request by dgboss**
This PR allows a user to select which weather model columns they would like to display for each weather parameter. Selections are save to local storage and restored when the app is re-opened with the same browser on the same computer.
# Test Links:
[Landing Page](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/)
[MoreCast 2.0](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/morecast-2)
[Percentile Calculator](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/percentile-calculator)
[MoreCast](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/morecast)
[C-Haines](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/c-haines)
[FireBat](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireBat bookmark](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN,s=9999&f=c7&c=NaN&w=NaN)
[Auto Spatial Advisory (ASA)](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/auto-spatial-advisory)
[HFI Calculator](https://wps-pr-3402.apps.silver.devops.gov.bc.ca/hfi-calculator)

### CODE REVIEW

**Comment by brettedw** [comment]
It's looking great! Looks like there might be a couple small bugs I came across 

   - cell double clicking seems to be broken again...seems annoyingly fragile
   - If you turn off all the tab groups, then turn one back on, you lose the Forecast column

**Comment by dgboss** [comment]
> It's looking great! Looks like there might be a couple small bugs I came across
> 
> * cell double clicking seems to be broken again...seems annoyingly fragile
> * If you turn off all the tab groups, then turn one back on, you lose the Forecast column

Thanks for taking a look! 

WRT double-clicking, my branch is likely stale. I'll update and test.

I'll look into the forecast column bug.

**Review by conbrad — APPROVED** [review]
Nice, do you think we should start some test coverage around some of this code?

**Review by conbrad — COMMENTED** [review]
Looks good, just commenting again to +1 Brett's findings, and wondering if we can test some of this stuff, maybe around the forecast column issue.

**Comment by dgboss** [comment]
Got the disappearing forecast bug resovled.

**Review by brettedw — APPROVED** [review]
Looks great!

**Pull request merged**
