### PR TITLE
Update sqlalchemy

### PR DESCRIPTION
**Pull request by dgboss**
Update sqlalchemy from 1.4 -> 2.0

I started with empty databases and applied all migrations for wps and tileserv. 
There is a bit of an issue with un-named constraints when trying to run `alembic downgrade base` for wps, but these issues are pre-existing. I'll create a dev task to address these issues.

I also smoke tested all the apps which revealed some minor issues that I addressed.
# Test Links:
[Landing Page](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/)
[MoreCast 2.0](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/morecast-2)
[Percentile Calculator](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/percentile-calculator)
[MoreCast](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/morecast)
[C-Haines](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/c-haines)
[FireBat](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator)
[FireBat bookmark](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/fire-behaviour-calculator?s=266&f=c5&c=NaN&w=20,s=286&f=c7&c=NaN&w=16,s=1055&f=c7&c=NaN&w=NaN,s=305&f=c7&c=NaN&w=NaN,s=344&f=c5&c=NaN&w=NaN,s=346&f=c7&c=NaN&w=NaN,s=328&f=c7&c=NaN&w=NaN,s=1399&f=c7&c=NaN&w=NaN,s=334&f=c7&c=NaN&w=NaN,s=1082&f=c3&c=NaN&w=NaN,s=388&f=c7&c=NaN&w=NaN,s=309&f=c7&c=NaN&w=16,s=306&f=c7&c=NaN&w=NaN,s=1029&f=c7&c=NaN&w=NaN,s=298&f=c7&c=NaN&w=NaN,s=836&f=c7&c=NaN&w=NaN,s=9999&f=c7&c=NaN&w=NaN)
[Auto Spatial Advisory (ASA)](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/auto-spatial-advisory)
[HFI Calculator](https://wps-pr-2711.apps.silver.devops.gov.bc.ca/hfi-calculator)

### CODE REVIEW

**Comment by dgboss** [comment]
Doh! Failing unit test. I'll fix this  on Monday.

**Review by conbrad — APPROVED** [review]
Thanks for this!

**Review by conbrad — CHANGES_REQUESTED** [review]
Some runtime errors I captured in chat to review on Monday

**Comment by dgboss** [comment]
> 

Thanks for looking into this. Unfortunately that will fix the unit test, but break things at runtime. In SQLAlchemy 2.0, rows are tuple like objects and can't be indexed into with a string. TO index via a string it looks like you can convert the row object into a dictionary via toDict() or something like that, or access row._mapping which is a dictionary that you can then index into. I'll revert the change and see if I can fix the unit test. I'll also close the PR as you suggested and open a new one.

**Pull request closed without merging**
